apiVersion: v1
kind: Secret
metadata:
  name: node-websocket-secret
type: Opaque
data:
  # Replace this with your base64 encoded DATABASE_URL.
  # Example: echo -n "postgresql://user:password@db-host:5432/db-name?schema=public" | base64
  DATABASE_URL: echo -n "postgresql://postgres:postgres@localhost:5432/websocket?schema=public" | base64
